// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXMqIGJFCO0XGGAD_PRdAqXB4iO7Oaw0',
    appId: '1:42299134512:web:2278faf05176678f5313f5',
    messagingSenderId: '42299134512',
    projectId: 'clstapp-f1cd7',
    authDomain: 'clstapp-f1cd7.firebaseapp.com',
    //storageBucket: 'clstapp-f1cd7.firebasestorage.app',
    storageBucket: 'clstapp-f1cd7.appspot.com',
    measurementId: 'G-7ZFY33GTV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiV8Z_bP3vrvMc8tRZQ9ZuZkyFRsL9g6M',
    appId: '1:42299134512:android:75329559d061a82c5313f5',
    messagingSenderId: '42299134512',
    projectId: 'clstapp-f1cd7',
    storageBucket: 'clstapp-f1cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsVCdljOzfee-MUgVzP89ZquUC_2xRYs',
    appId: '1:42299134512:ios:d0c3deca8d56d0a85313f5',
    messagingSenderId: '42299134512',
    projectId: 'clstapp-f1cd7',
    storageBucket: 'clstapp-f1cd7.firebasestorage.app',
    iosClientId: '42299134512-dv4dvils1hacijrllcdt4e7vdknceh14.apps.googleusercontent.com',
    iosBundleId: 'com.example.clstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsVCdljOzfee-MUgVzP89ZquUC_2xRYs',
    appId: '1:42299134512:ios:d0c3deca8d56d0a85313f5',
    messagingSenderId: '42299134512',
    projectId: 'clstapp-f1cd7',
    storageBucket: 'clstapp-f1cd7.firebasestorage.app',
    iosClientId: '42299134512-dv4dvils1hacijrllcdt4e7vdknceh14.apps.googleusercontent.com',
    iosBundleId: 'com.example.clstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpXMqIGJFCO0XGGAD_PRdAqXB4iO7Oaw0',
    appId: '1:42299134512:web:d32918c2afab30395313f5',
    messagingSenderId: '42299134512',
    projectId: 'clstapp-f1cd7',
    authDomain: 'clstapp-f1cd7.firebaseapp.com',
    storageBucket: 'clstapp-f1cd7.firebasestorage.app',
    measurementId: 'G-NQCTJ834EH',
  );

}